[package]
name = "rust-g"
edition = "2021"
version = "1.2.0+a"
authors = [
    "Bjorn Neergaard <bjorn@neersighted.com>",
    "Tad Hardesty <tad@platymuus.com>",
    "rust-g maintainer team",
]
repository = "https://github.com/tgstation/rust-g"
license = "MIT"
description = "Offloaded task library for the /tg/ Space Station 13 codebase"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = true

[dependencies]
thiserror = "1.0"
flume = { version = "0.10", optional = true }
chrono = { version = "0.4", optional = true }
base64 = { version = "0.13", optional = true }
md-5 = { version = "0.10", optional = true }
twox-hash = { version = "1.6", optional = true }
const-random = { version = "0.1.13", optional = true }
sha-1 = { version = "0.10", optional = true }
sha2 = { version = "0.10", optional = true }
hex = { version = "0.4", optional = true }
percent-encoding = { version = "2.1", optional = true }
url-dep = { version = "2.1", package = "url", optional = true }
png = { version = "0.17", optional = true }
image = { version = "0.24", optional = true, default-features = false, features = [
    "png",
] }
git2 = { version = "0.14", optional = true, default-features = false }
noise = { version = "0.8", optional = true }
redis = { version = "0.21", optional = true }
reqwest = { version = "0.11", optional = true, default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }
lazy_static = { version = "1.4", optional = true }
once_cell = { version = "1.4", optional = true }
mysql = { version = "22.2", optional = true }
dashmap = { version = "5.3", optional = true }
zip = { version = "0.6", optional = true }
rand = { version = "0.8", optional = true }
toml-dep = { version = "0.5.8", package = "toml", optional = true }
aho-corasick = { version = "0.7.18", optional = true }
rayon = { version = "1.5", optional = true }
dbpnoise = { version = "0.1.2", optional = true }
pathfinding = { version = "3.0.13", optional = true }
num = { version = "0.4.0", optional = true }
fast_poisson = { version = "0.5.2", optional = true }
dmm_parser_rs = { git = "https://github.com/DreamySkrell/dmm_parser_rs", rev = "1857bf7c3877205f75cff57f4f57c4197dfe2c9f", optional = true }

[features]
default = [
    "acreplace",
    # Aurora special snowflake noise gen
    "auroranoise",
    # Not default either but we need it
    "batchnoise",
    "cellularnoise",
    "dmi",
    "file",
    "git",
    # Not included by default, but we use it
    "hash",
    "http",
    "json",
    "log",
    "noise",
    "sql",
    "time",
    "toml",
    # Aurora special nowflake module, because of course we have one
    "udp",
    "url",
    "mapmanip",
]

# default features
acreplace = ["aho-corasick"]
auroranoise = ["fast_poisson"]
cellularnoise = ["rand", "rayon"]
dmi = ["png", "image"]
file = []
git = ["git2", "chrono"]
http = ["reqwest", "serde", "serde_json", "once_cell", "jobs"]
json = ["serde", "serde_json"]
log = ["chrono"]
sql = ["mysql", "serde", "serde_json", "once_cell", "dashmap", "jobs"]
time = []
toml = ["serde", "serde_json", "toml-dep"]
udp = []
url = ["url-dep", "percent-encoding"]
mapmanip = ["dmm_parser_rs", "file", "rand", "serde", "serde_json"]

# additional features
batchnoise = ["dbpnoise"]
hash = [
    "base64",
    "const-random",
    "md-5",
    "hex",
    "sha-1",
    "sha2",
    "twox-hash",
    "serde",
    "serde_json",
]
pathfinder = ["num", "pathfinding", "serde", "serde_json"]
redis_pubsub = ["flume", "redis", "serde", "serde_json"]
unzip = ["zip", "jobs"]
worleynoise = ["rand", "rayon"]

# internal feature-like things
jobs = ["flume"]

[dev-dependencies]
regex = "1"

[patch.crates-io.funty]
git = "https://github.com/ferrilab/funty.git"
rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446"
